import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "@/styles/layout.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
          </header>
          <main className={styles.main}>{children}</main>
          <footer className={styles.footer}>
            <p>&copy; 2024 Bestseller App</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
